[package]
name = "concrete_syntax"
description = "Concrete syntax pattern matching library with Rust and WASM support"
license-file = "../../LICENSE"

version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# Core dependencies
tree-sitter = { version = "0.20.6", optional = true }
tree-sitter-traversal = { version = "0.1.2", optional = true }
pest = "2.7"
pest_derive = "2.7"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# WASM dependencies
wasm-bindgen = { version = "0.2", optional = true }
js-sys = { version = "0.3", optional = true }
web-sys = { version = "0.3", features = ["console"], optional = true }
serde-wasm-bindgen = { version = "0.6", optional = true }
regex = { workspace = true }

[features]
default = ["native"]
native = ["tree-sitter", "tree-sitter-traversal"]
wasm = ["wasm-bindgen", "js-sys", "web-sys", "serde-wasm-bindgen"]


[dev-dependencies]
wasm-bindgen-test = "0.3"
tree-sitter-kotlin = { git = "https://github.com/danieltrt/tree-sitter-kotlin", rev = "5e0b07cb2ba628842028313b60b97699cc5e0fee" }
tree-sitter-java = "0.20.2"
# TODO: Update after: https://github.com/alex-pinkus/tree-sitter-swift/issues/278 resolves
tree-sitter-swift = { git = "https://github.com/satyam1749/tree-sitter-swift.git", rev = "08a28993599f1968bc81631a89690503e1db7704" }
tree-sitter-python = "0.20.2"
tree-sitter-ruby = "0.20.1"
tree-sitter-typescript = "0.20.1"
# TODO: Update after https://github.com/tree-sitter/tree-sitter-go/pull/103 lands
tree-sitter-go = { git = "https://github.com/danieltrt/tree-sitter-go.git", rev = "ea5ceb716012db8813a2c05fab23c3a020988724" }
