name: Detect Changes

on:
  workflow_call:

jobs:
  # runs change detection
  # this job allows build to have a single if
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: '.github/filters.yaml'
