name: Deploy Tree-sitter Playground

on:
  push:
    branches: [ master ]
    paths:
      - 'playground/tree-sitter/**'
      - '**/Cargo.toml'
      - '.github/workflows/release_tree_sitter_playground.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install tree-sitter CLI
      # We have to lock tree-sitter CLI to 0.24 since newer CLI does not support building
      # the old grammars we use in Piranha.
      run: cargo install tree-sitter-cli --version "=0.24"

    - name: Build playground
      run: python build.py --dist-dir ./dist/tree-sitter-playground
      working-directory: playground/tree-sitter

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: playground/tree-sitter/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
