name: Node.js

on:
  pull_request:
    branches: [ master ]

jobs:
  detect:
    uses: ./.github/workflows/detect_changes.yml

  build:
    runs-on: ubuntu-latest
    needs: detect
    if: ${{ needs.detect.outputs.js == 'false' }}

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - run: 'echo "No JS changes; build is not required." '
