# GitHub CI workflow for PiranhaSwift

name: Swift CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-11
    strategy:
        matrix:
          xcode: ['13.0']
    name: "PiranhaSwift using ${{ matrix.xcode }} on ${{ matrix.os }}"
    steps:
      - name: Check out Piranha sources
        uses: actions/checkout@v2
      - name: Set Xcode ${{ matrix.xcode }}
        run: |
         sudo xcode-select -s /Applications/Xcode_13.0_beta.app
         xcodebuild -version
         swift --version
         swift package --version
      - name: Build and test
        run: |
           cd swift/
           sh package.sh
           sh test.sh
